---
name: Mutator CI
on:
  push:
    # branches:
    #   - main
    # paths-ignore:
    #   - .github/workflows/mutator.yaml
    #   - .github/workflows/main.yaml
jobs:
  mutator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.15.x"
      - run: sudo apt-get update
      - run: sudo apt-get install -y tzdata
      - run: sudo ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
      - run: yarn
      - run: yarn test-ci
      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" \
          >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Mutator run mutator
        run: |
          yarn stryker-mutate --reporters dashboard \
          --dashboard.version ${{ steps.extract_branch.outputs.branch }}
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRIKER_MUTATOR_TOKEN  }}
